env:
  node: true
extends:
  - airbnb
rules:
  comma-dangle:
    - 2
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
